Made setting of GIT_CRYPT_KEY work with peass-ci-plugin
DaGeRe/peass pull request #79
Opened 2022-07-18 12:51 UTC by mawHBT

Repo is also unlocked in ContinuousFolderUtil if GIT_CRYPT_KEY is set in Environment.
An Exception is thrown, if unlocking did not succeed.
Some comments have been added, why TestGitUtilsGitCrypt.testCheckIsUnlockedWithGitCrypt ist disabled and GitUtils.checkIsUnlockedWithGitCrypt will not work, if jenkins is started with `mvn hpi:run`.

2022-07-18 13:04 UTC, DaGeRe requested changes
Thanks for the PR, please refactor `ContinuousFolderUtil` before merging.

2022-07-19 10:13 UTC, mawHBT commented on analysis/src/main/java/de/dagere/peass/ci/ContinuousFolderUtil.java
> +      final String projectName = projectName_fullPeass.substring(0, projectName_fullPeass.length() - new String("_fullPeass").length());
Using originalVcsFolder.getName() is much simpler, thanks for the hint! So I removed getProjectSubfolder().

2022-07-19 10:19 UTC, DaGeRe commented
Looks fine, thanks for the PR!

2022-07-19 10:19 UTC, merged

2022-07-19 10:42 UTC, mawHBT commented
This was tested on a local jenkins with all the expected results.